# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
            SalleBundle\Entity\User:
              algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory: { memory: null}
        in_database:
            entity:
                class: SalleBundle\Entity\User
                property: email
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider : in_database
            form_login:
                login_path: salle_connexion_user
                check_path: salle_connexion_user
                default_target_path: salle_affichage_abonner
            logout:
                path: salle_deconnexion_user
                target: salle_connexion_user
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
