<?php
/**
 * Created by PhpStorm.
 * User: Moatez
 * Date: 04/01/2021
 * Time: 22:54
 */

namespace SalleBundle\Form;


use Symfony\Component\Form\AbstractType;
use \Symfony\Component\Form\FormBuilderInterface;
use \Symfony\Component\Form\Extension\Core\Type\TextareaType;
class ActiviterForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('jour',TextareaType::class,['attr'=>['class'=>'input']])
            ->add('nom',TextareaType::class,['attr'=>['class'=>'input']])
            ->add('heure',TextareaType::class,['attr'=>['class'=>'input']]);


        // TODO: Change the autogenerated stub
    }
    public function getName(){

        return 'Activiter';
    }

}