<?php
namespace SalleBundle\Form;
/**
 * Created by PhpStorm.
 * User: Moatez
 * Date: 17/11/2020
 * Time: 11:40
 */
use function Sodium\add;
use \Symfony\Component\Form\AbstractType;
use \Symfony\Component\Form\FormBuilderInterface;
use \Symfony\Component\Form\Extension\Core\Type\TextareaType;
class ModeleForm extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nem',TextareaType::class,['attr'=>['class'=>'input']])
            ->add('prenom',TextareaType::class,['attr'=>['class'=>'input']])
            ->add('num',TextareaType::class,['attr'=>['class'=>'input']])
            ->add('tarif',TextareaType::class,['attr'=>['class'=>'input']])
            ->add('type',TextareaType::class,['attr'=>['class'=>'input']])
            ->add('periode',TextareaType::class,['attr'=>['class'=>'input']]);


        // TODO: Change the autogenerated stub
    }
    public function getName(){

        return 'Abonner';
    }


}